export type postListConstants = {
    userphoto: string,
    username: string,
    datetime: string,
    likes: number,
    comments: number,
    postphoto: string,
    content: string,
    posttype: string,
    postlog: string,
    postuserid: string,
    likelist: string[],
    nickname: string,
    isfollow: boolean,
    currentPlayingIndex: number,
    setCurrentPlayingIndex: (index: number) => void,
    isMuted: boolean,
    setIsMuted: (muted: boolean) => void,
    setShowAction: (show: boolean) => void,
    index: number,
    showAction: boolean,
    timeoutId: NodeJS.Timeout | null,
    setPosts: React.Dispatch<React.SetStateAction<any[]>>,
    isProfilePage?: boolean,
    creatorId?: string,
    followers?: string[],
  }